# ===== 尺度与安全 =====
UNIT_TO_M = 0.35 / 4.0
CELL_METERS = UNIT_TO_M
ROBOT_W_M = 0.20
ROBOT_L_M = 0.20
MIN_WALL_CLEARANCE = 0.10
RETURN_CLEARANCE_M  = 0.10
EPS_ON_WALL = 1e-5

# ===== 运行/等待 =====
FAST_TEST = False
if FAST_TEST:
    TURN_TIME = 0.25
    SIM_STEP_SLEEP = 0.02
else:
    TURN_TIME = 0.40
    SIM_STEP_SLEEP = 0.02
ACTION_GAP_SEC = 1.0
CAR_NOMINAL_SPEED_MPS = 0.10

# ===== SLAM/Lidar=====
MAP_SIZE = 1000
MAP_RES = 0.01
LIDAR_MAX_RANGE = 8.0
LIDAR_ANG_RES_DEG = 4.0
MOVE_VISIBLE_RADIUS = 2.0

# ===== 扫描策略 =====
SCAN_INTERVAL_M = 0.70
START_SCAN_SEC  = 10.0
PERIODIC_SCAN_SEC = 10.0
